# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iOS Developer
email: ajaykumar21091@gmail.com
description: 
url: https:/ajaykumar21091.github.io # the base hostname & protocol for your site
#twitter_username: jekyllrb
facebook_username: ajay kumar yadav
github_username:  ajaykumar21091

# Build settings
markdown: kramdown
